# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: serve

  serve:
    desc: Run username/password auth example server on :8081
    cmds:
      - go run .

  dev:
    desc: Run username/password auth example server with air on :8081
    cmds:
      - air
